#ifndef _NAPOCA_BUILDCONFIG_H_
#define _NAPOCA_BUILDCONFIG_H_

#define CFG_DEBUG_TRACE_SPINLOCKS                        1
#define CFG_FEATURES_CMDLINE_ENABLED                     1
#define CFG_FEATURES_OPENSSLSUPPORT                      1


#define SYMBOL_LIST                                      {"CFG_DEBUG_TRACE_SPINLOCKS", UD_TYPE_NUMBER, (UD_NUMBER) CFG_DEBUG_TRACE_SPINLOCKS},\
{"CFG_FEATURES_CMDLINE_ENABLED", UD_TYPE_NUMBER, (UD_NUMBER) CFG_FEATURES_CMDLINE_ENABLED},\
{"CFG_FEATURES_OPENSSLSUPPORT", UD_TYPE_NUMBER, (UD_NUMBER) CFG_FEATURES_OPENSSLSUPPORT}

#endif
