/*
* Copyright (c) 2020 Bitdefender
* SPDX-License-Identifier: Apache-2.0
*/


#ifndef _WINGUEST_STATUS_H_
#define _WINGUEST_STATUS_H_

#include "cx_status_defs.h"


#define REQUIRED_FEATURES_BASE               (0x8000)

#define REQUIRED_FEATURES_MASK                          CX_MAKE_STATUS(CX_STATUS_SEVERITY_ERROR, CX_FACILITY_DACIA_WINGUEST, REQUIRED_FEATURES_BASE)

#ifndef NT_SUCCESS
#define NT_SUCCESS(Status) (((NTSTATUS)(Status)) >= 0)
#endif

#define STATUS_FROM_WIN32_ERROR                         ((NTSTATUS)0xE8F00000L) // | Win32 error from GetLastError()
#define WIN32_TO_NTSTATUS(Win32Error)                   (STATUS_FROM_WIN32_ERROR | ((Win32Error) & 0x0000FFFF))


// WINGUEST SPECIFIC ERROR STATUS
#define STATUS_VERSION_INCOMPATIBLE                     CX_MAKE_STATUS(CX_STATUS_SEVERITY_ERROR, CX_FACILITY_DACIA_WINGUEST, 0x0001L)
#define STATUS_HYPERVISOR_ALREADY_STARTED               CX_MAKE_STATUS(CX_STATUS_SEVERITY_ERROR, CX_FACILITY_DACIA_WINGUEST, 0x0002L)
#define STATUS_HYPERVISOR_NOT_STARTED                   CX_MAKE_STATUS(CX_STATUS_SEVERITY_ERROR, CX_FACILITY_DACIA_WINGUEST, 0x0003L)
#define STATUS_USERMODE_DRIVER_NOT_CONNECTED            CX_MAKE_STATUS(CX_STATUS_SEVERITY_ERROR, CX_FACILITY_DACIA_WINGUEST, 0x0004L)
#define STATUS_DRIVER_HYPERVISOR_NOT_CONNECTED          CX_MAKE_STATUS(CX_STATUS_SEVERITY_ERROR, CX_FACILITY_DACIA_WINGUEST, 0x0005L)
#define STATUS_DRIVER_CONNECTION_ACTIVE                 CX_MAKE_STATUS(CX_STATUS_SEVERITY_ERROR, CX_FACILITY_DACIA_WINGUEST, 0x0006L)
#define STATUS_HV_CONFIGURATION_NOT_SUPPORTED           CX_MAKE_STATUS(CX_STATUS_SEVERITY_ERROR, CX_FACILITY_DACIA_WINGUEST, 0x0007L)
#define STATUS_HYPERVISOR_NOT_CONFIGURED                CX_MAKE_STATUS(CX_STATUS_SEVERITY_ERROR, CX_FACILITY_DACIA_WINGUEST, 0x0008L)
#define STATUS_NOT_PROPERLY_CONFIGURED                  CX_MAKE_STATUS(CX_STATUS_SEVERITY_ERROR, CX_FACILITY_DACIA_WINGUEST, 0x0009L)
#define STATUS_INTROSPECTION_OPERATION_NOT_SUPPORTED    CX_MAKE_STATUS(CX_STATUS_SEVERITY_ERROR, CX_FACILITY_DACIA_WINGUEST, 0x000AL)
#define STATUS_INVALID_SDK_FOLDER                       CX_MAKE_STATUS(CX_STATUS_SEVERITY_ERROR, CX_FACILITY_DACIA_WINGUEST, 0x000BL)
#define STATUS_COMPONENT_NOT_KNOWN                      CX_MAKE_STATUS(CX_STATUS_SEVERITY_ERROR, CX_FACILITY_DACIA_WINGUEST, 0x000CL)
#define STATUS_UNKNOWN_HW_ID                            CX_MAKE_STATUS(CX_STATUS_SEVERITY_ERROR, CX_FACILITY_DACIA_WINGUEST, 0x000DL)
#define STATUS_INVALID_WG_CALLBACK_ID                   CX_MAKE_STATUS(CX_STATUS_SEVERITY_ERROR, CX_FACILITY_DACIA_WINGUEST, 0x000EL)
#define STATUS_WG_NOT_INITIALIZED                       CX_MAKE_STATUS(CX_STATUS_SEVERITY_ERROR, CX_FACILITY_DACIA_WINGUEST, 0x000FL)
#define STATUS_WG_ALREADY_INITIALIZED                   CX_MAKE_STATUS(CX_STATUS_SEVERITY_ERROR, CX_FACILITY_DACIA_WINGUEST, 0x0010L)
#define STATUS_WINGUEST_EXCEPTION_ENCOUNTERED           CX_MAKE_STATUS(CX_STATUS_SEVERITY_ERROR, CX_FACILITY_DACIA_WINGUEST, 0x0011L)
#define STATUS_JSON_EXCEPTION_ENCOUNTERED               CX_MAKE_STATUS(CX_STATUS_SEVERITY_ERROR, CX_FACILITY_DACIA_WINGUEST, 0x0012L)

#define STATUS_UPDATE_RECOMMENDS_REBOOT                 CX_MAKE_STATUS(CX_STATUS_SEVERITY_ERROR, CX_FACILITY_DACIA_WINGUEST, 0x1000L)
#define STATUS_UPDATE_REQUEST_REBOOT_FOR_UPDATE         CX_MAKE_STATUS(CX_STATUS_SEVERITY_ERROR, CX_FACILITY_DACIA_WINGUEST, 0x1001L)
#define STATUS_UPDATE_REQUIRES_REBOOT                   CX_MAKE_STATUS(CX_STATUS_SEVERITY_ERROR, CX_FACILITY_DACIA_WINGUEST, 0x1002L)
#define STATUS_UPDATE_FILE_ERROR                        CX_MAKE_STATUS(CX_STATUS_SEVERITY_ERROR, CX_FACILITY_DACIA_WINGUEST, 0x1003L)



// WINGUEST error status related to required features for hv
#define STATUS_UNSUPPORTED_PLATFORM                     CX_MAKE_STATUS(CX_STATUS_SEVERITY_ERROR, CX_FACILITY_DACIA_WINGUEST, 0x8000L)
#define STATUS_UNSUPPORTED_CPU                          CX_MAKE_STATUS(CX_STATUS_SEVERITY_ERROR, CX_FACILITY_DACIA_WINGUEST, 0x8001L)
#define STATUS_VMX_FEATURES_LOCKED_DISABLED             CX_MAKE_STATUS(CX_STATUS_SEVERITY_ERROR, CX_FACILITY_DACIA_WINGUEST, 0x8002L)
#define STATUS_VIRTUALIZATION_FEATURES_NOT_AVAILABLE    CX_MAKE_STATUS(CX_STATUS_SEVERITY_ERROR, CX_FACILITY_DACIA_WINGUEST, 0x8003L)
#define STATUS_GRUB_FILES_MISSING                       CX_MAKE_STATUS(CX_STATUS_SEVERITY_ERROR, CX_FACILITY_DACIA_WINGUEST, 0x8004L)
#define STATUS_MBR_CONFIGURATION_NOT_SUPPORTED          CX_MAKE_STATUS(CX_STATUS_SEVERITY_ERROR, CX_FACILITY_DACIA_WINGUEST, 0x8005L)
#define STATUS_NOT_SUPPORTED_WHILE_IN_VM                CX_MAKE_STATUS(CX_STATUS_SEVERITY_ERROR, CX_FACILITY_DACIA_WINGUEST, 0x8006L)
#define STATUS_SDK_FILES_MISSING                        CX_MAKE_STATUS(CX_STATUS_SEVERITY_ERROR, CX_FACILITY_DACIA_WINGUEST, 0x8007L)
#define STATUS_OS_VERSION_NOT_SUPPORTED                 CX_MAKE_STATUS(CX_STATUS_SEVERITY_ERROR, CX_FACILITY_DACIA_WINGUEST, 0x8008L)
#define STATUS_CANNOT_GET_SYSTEM_CONFIGURATION          CX_MAKE_STATUS(CX_STATUS_SEVERITY_ERROR, CX_FACILITY_DACIA_WINGUEST, 0x8009L)
#define STATUS_PREVIOUS_GRUB_FILES_DETECTED             CX_MAKE_STATUS(CX_STATUS_SEVERITY_ERROR, CX_FACILITY_DACIA_WINGUEST, 0x800AL)
#define STATUS_BOOT_ORDER_OVERRIDEN                     CX_MAKE_STATUS(CX_STATUS_SEVERITY_ERROR, CX_FACILITY_DACIA_WINGUEST, 0x800BL)
#define STATUS_INSUFFICIENT_PHYSICAL_MEMORY             CX_MAKE_STATUS(CX_STATUS_SEVERITY_ERROR, CX_FACILITY_DACIA_WINGUEST, 0x800CL)

// WINGUEST SPECIFIC WARNING STATUS
#define STATUS_DEVICE_INSTALL_REQUIRES_RESTART          CX_MAKE_STATUS(CX_STATUS_SEVERITY_WARNING, CX_FACILITY_DACIA_WINGUEST, 0x0001L)
#define STATUS_DEVICE_UNINSTALL_REQUIRES_RESTART        CX_MAKE_STATUS(CX_STATUS_SEVERITY_WARNING, CX_FACILITY_DACIA_WINGUEST, 0x0002L)

// WINGUEST SPECIFIC INFORMATIONAL STATUS
#define STATUS_CONFIGURATION_REQUIRES_RESTART           CX_MAKE_STATUS(CX_STATUS_SEVERITY_INFORMATIONAL, CX_FACILITY_DACIA_WINGUEST, 0x0001L)
#define STATUS_INTROSPECTION_ENGINE_RESTARTED           CX_MAKE_STATUS(CX_STATUS_SEVERITY_INFORMATIONAL, CX_FACILITY_DACIA_WINGUEST, 0x0002L)

#endif // _WINGUEST_STATUS_H_

