/*
* Copyright (c) 2020 Bitdefender
* SPDX-License-Identifier: Apache-2.0
*/

#ifndef _VERSION_H_
#define _VERSION_H_

#include "ver.h" // global version file

#define WINGUESTDLL_VERSION_HIGH        GLOBAL_VERSION_MAJOR
#define WINGUESTDLL_VERSION_LOW         GLOBAL_VERSION_MINOR
#define WINGUESTDLL_VERSION_REVISION    GLOBAL_VERSION_REVISION
#define WINGUESTDLL_VERSION_BUILD       GLOBAL_VERSION_BUILDNUMBER

#define WINGUESTDLL_BUILD_DATE          __DATE__
#define WINGUESTDLL_BUILD_TIME          __TIME__

#define WINGUESTDLL_VERSIONSTAMP        ((((DWORD)WINGUESTDLL_VERSION_HIGH) << 30) | (((DWORD)WINGUESTDLL_VERSION_LOW) << 24) |        \
                                        (((DWORD)WINGUESTDLL_VERSION_REVISION) << 16) | ((DWORD)WINGUESTDLL_VERSION_BUILD))

#ifdef DEBUG
#define VER_FILEDESCRIPTION_STR         "WINGUEST communication library (DEBUG)"
#else
#define VER_FILEDESCRIPTION_STR         "WINGUEST communication library"
#endif

#define VER_INTERNALNAME_STR            "winguestdll.dll"

#define VER_ORIGINALFILENAME_STR        VER_INTERNALNAME_STR

#ifdef VER_LEGALCOPYRIGHT_STR
#undef VER_LEGALCOPYRIGHT_STR
#endif
#define VER_LEGALCOPYRIGHT_STR          "\251 NapocaHv All rights reserved."

#ifdef VER_COMPANYNAME_STR
#undef VER_COMPANYNAME_STR
#endif
#define VER_COMPANYNAME_STR             "NapocaHv Bucharest, ROMANIA"

#ifdef VER_PRODUCTNAME_STR
#undef VER_PRODUCTNAME_STR
#endif
#define VER_PRODUCTNAME_STR             "NapocaHv \256 AntiVirus"

#define VER_PRODUCTVERSION              WINGUESTDLL_VERSION_HIGH,WINGUESTDLL_VERSION_LOW,WINGUESTDLL_VERSION_REVISION,WINGUESTDLL_VERSION_BUILD

#ifdef VER_FILEVERSION
#undef VER_FILEVERSION
#endif
#define VER_FILEVERSION                 WINGUESTDLL_VERSION_HIGH,WINGUESTDLL_VERSION_LOW,WINGUESTDLL_VERSION_REVISION,WINGUESTDLL_VERSION_BUILD

#ifdef DEBUG
#define BDVER_FILEVERSION_MAJORMINORREVBLD2(x,y,z,w) #x "." #y "." #z "." #w ", DEBUG"
#else
#define BDVER_FILEVERSION_MAJORMINORREVBLD2(x,y,z,w) #x "." #y "." #z "." #w
#endif
#define BDVER_FILEVERSION_MAJORMINORREVBLD1(x,y,z,w) BDVER_FILEVERSION_MAJORMINORREVBLD2(x, y, z, w)

#ifdef VER_FILEVERSION_STR
#undef VER_FILEVERSION_STR
#endif
#define VER_FILEVERSION_STR             BDVER_FILEVERSION_MAJORMINORREVBLD1(WINGUESTDLL_VERSION_HIGH, WINGUESTDLL_VERSION_LOW, WINGUESTDLL_VERSION_REVISION, WINGUESTDLL_VERSION_BUILD)

#ifdef VER_PRODUCTVERSION_STR
#undef VER_PRODUCTVERSION_STR
#endif
#define VER_PRODUCTVERSION_STR          BDVER_FILEVERSION_MAJORMINORREVBLD1(WINGUESTDLL_VERSION_HIGH, WINGUESTDLL_VERSION_LOW, WINGUESTDLL_VERSION_REVISION, WINGUESTDLL_VERSION_BUILD)
#endif // _VERSION_H_
