/*
* Copyright (c) 2020 Bitdefender
* SPDX-License-Identifier: Apache-2.0
*/

//
// Provides a standard set of generic (core/native) CX_STATUS definitions to be used across CODEX-based projects
//
#ifndef _CX_STATUS_H_
#define _CX_STATUS_H_

#include "cx_status_defs.h"

//
// Success value(s)
//
#define CX_STATUS_SUCCESS                       ((CX_STATUS_TYPECAST)0) 

//
// parameter validation errors
//
#define CX_STATUS_INVALID_PARAMETER             CX_MAKE_STATUS(CX_STATUS_SEVERITY_ERROR, CX_FACILITY_CODEX_NATIVE, 0x00) 
#define CX_STATUS_INVALID_PARAMETER_1           CX_MAKE_STATUS(CX_STATUS_SEVERITY_ERROR, CX_FACILITY_CODEX_NATIVE, 0x01) 
#define CX_STATUS_INVALID_PARAMETER_2           CX_MAKE_STATUS(CX_STATUS_SEVERITY_ERROR, CX_FACILITY_CODEX_NATIVE, 0x02) 
#define CX_STATUS_INVALID_PARAMETER_3           CX_MAKE_STATUS(CX_STATUS_SEVERITY_ERROR, CX_FACILITY_CODEX_NATIVE, 0x03) 
#define CX_STATUS_INVALID_PARAMETER_4           CX_MAKE_STATUS(CX_STATUS_SEVERITY_ERROR, CX_FACILITY_CODEX_NATIVE, 0x04) 
#define CX_STATUS_INVALID_PARAMETER_5           CX_MAKE_STATUS(CX_STATUS_SEVERITY_ERROR, CX_FACILITY_CODEX_NATIVE, 0x05) 
#define CX_STATUS_INVALID_PARAMETER_6           CX_MAKE_STATUS(CX_STATUS_SEVERITY_ERROR, CX_FACILITY_CODEX_NATIVE, 0x06) 
#define CX_STATUS_INVALID_PARAMETER_7           CX_MAKE_STATUS(CX_STATUS_SEVERITY_ERROR, CX_FACILITY_CODEX_NATIVE, 0x07) 
#define CX_STATUS_INVALID_PARAMETER_8           CX_MAKE_STATUS(CX_STATUS_SEVERITY_ERROR, CX_FACILITY_CODEX_NATIVE, 0x08) 
#define CX_STATUS_INVALID_PARAMETER_9           CX_MAKE_STATUS(CX_STATUS_SEVERITY_ERROR, CX_FACILITY_CODEX_NATIVE, 0x09) 
#define CX_STATUS_INVALID_PARAMETER_10          CX_MAKE_STATUS(CX_STATUS_SEVERITY_ERROR, CX_FACILITY_CODEX_NATIVE, 0x0A) 
#define CX_STATUS_INVALID_PARAMETER_11          CX_MAKE_STATUS(CX_STATUS_SEVERITY_ERROR, CX_FACILITY_CODEX_NATIVE, 0x0B) 
#define CX_STATUS_INVALID_PARAMETER_12          CX_MAKE_STATUS(CX_STATUS_SEVERITY_ERROR, CX_FACILITY_CODEX_NATIVE, 0x0C) 
#define CX_STATUS_INVALID_PARAMETER_MIX         CX_MAKE_STATUS(CX_STATUS_SEVERITY_ERROR, CX_FACILITY_CODEX_NATIVE, 0x0D)

//
// module/subsystem errors
//
#define CX_STATUS_COMPONENT_NOT_INITIALIZED     CX_MAKE_STATUS(CX_STATUS_SEVERITY_ERROR, CX_FACILITY_CODEX_NATIVE, 0x00 + 0x100)
#define CX_STATUS_COMPONENT_ALREADY_INITIALIZED CX_MAKE_STATUS(CX_STATUS_SEVERITY_ERROR, CX_FACILITY_CODEX_NATIVE, 0x01 + 0x100)
#define CX_STATUS_COMPONENT_NOT_READY           CX_MAKE_STATUS(CX_STATUS_SEVERITY_ERROR, CX_FACILITY_CODEX_NATIVE, 0x02 + 0x100)
#define CX_STATUS_COMPONENT_NOT_FOUND           CX_MAKE_STATUS(CX_STATUS_SEVERITY_ERROR, CX_FACILITY_CODEX_NATIVE, 0x03 + 0x100)
#define CX_STATUS_COMPONENT_LIFECYCLE_ENDED     CX_MAKE_STATUS(CX_STATUS_SEVERITY_ERROR, CX_FACILITY_CODEX_NATIVE, 0x04 + 0x100)
#define CX_STATUS_INVALID_COMPONENT_STATE       CX_MAKE_STATUS(CX_STATUS_SEVERITY_ERROR, CX_FACILITY_CODEX_NATIVE, 0x05 + 0x100)

#define CX_STATUS_OPERATION_NOT_SUPPORTED       CX_MAKE_STATUS(CX_STATUS_SEVERITY_ERROR, CX_FACILITY_CODEX_NATIVE, 0x06 + 0x100)
#define CX_STATUS_OPERATION_NOT_IMPLEMENTED     CX_MAKE_STATUS(CX_STATUS_SEVERITY_ERROR, CX_FACILITY_CODEX_NATIVE, 0x07 + 0x100)
#define CX_STATUS_INVALID_OPERATION_STATE       CX_MAKE_STATUS(CX_STATUS_SEVERITY_ERROR, CX_FACILITY_CODEX_NATIVE, 0x08 + 0x100)
#define CX_STATUS_COMPONENT_BUSY                CX_MAKE_STATUS(CX_STATUS_SEVERITY_ERROR, CX_FACILITY_CODEX_NATIVE, 0x09 + 0x100)

//
// data/buffer errors
//
#define CX_STATUS_INVALID_DATA_VALUE            CX_MAKE_STATUS(CX_STATUS_SEVERITY_ERROR, CX_FACILITY_CODEX_NATIVE, 0x00 + 0x200)
#define CX_STATUS_INVALID_DATA_TYPE             CX_MAKE_STATUS(CX_STATUS_SEVERITY_ERROR, CX_FACILITY_CODEX_NATIVE, 0x01 + 0x200)
#define CX_STATUS_INVALID_DATA_SIZE             CX_MAKE_STATUS(CX_STATUS_SEVERITY_ERROR, CX_FACILITY_CODEX_NATIVE, 0x02 + 0x200)

// valid and supported most likely but some kind of redundant information is available and that info is contradictory
#define CX_STATUS_INCONSISTENT_DATA_VALUE       CX_MAKE_STATUS(CX_STATUS_SEVERITY_ERROR, CX_FACILITY_CODEX_NATIVE, 0x03 + 0x200)
#define CX_STATUS_INCONSISTENT_DATA_SIZE        CX_MAKE_STATUS(CX_STATUS_SEVERITY_ERROR, CX_FACILITY_CODEX_NATIVE, 0x04 + 0x200)
#define CX_STATUS_CORRUPTED_DATA                CX_MAKE_STATUS(CX_STATUS_SEVERITY_ERROR, CX_FACILITY_CODEX_NATIVE, 0x05 + 0x200)
                                                                                                                       
#define CX_STATUS_DATA_NOT_INITIALIZED          CX_MAKE_STATUS(CX_STATUS_SEVERITY_ERROR, CX_FACILITY_CODEX_NATIVE, 0x06 + 0x200)
#define CX_STATUS_DATA_IN_USE                   CX_MAKE_STATUS(CX_STATUS_SEVERITY_ERROR, CX_FACILITY_CODEX_NATIVE, 0x07 + 0x200)
#define CX_STATUS_DATA_ALREADY_EXISTS           CX_MAKE_STATUS(CX_STATUS_SEVERITY_ERROR, CX_FACILITY_CODEX_NATIVE, 0x08 + 0x200)
#define CX_STATUS_DATA_ALREADY_INITIALIZED      CX_MAKE_STATUS(CX_STATUS_SEVERITY_ERROR, CX_FACILITY_CODEX_NATIVE, 0x09 + 0x200)
#define CX_STATUS_DATA_ALREADY_FREE             CX_MAKE_STATUS(CX_STATUS_SEVERITY_ERROR, CX_FACILITY_CODEX_NATIVE, 0x0A + 0x200)
#define CX_STATUS_DATA_NOT_FOUND                CX_MAKE_STATUS(CX_STATUS_SEVERITY_ERROR, CX_FACILITY_CODEX_NATIVE, 0x0B + 0x200)
#define CX_STATUS_DATA_NOT_READY                CX_MAKE_STATUS(CX_STATUS_SEVERITY_ERROR, CX_FACILITY_CODEX_NATIVE, 0x0C + 0x200)
#define CX_STATUS_DATA_LIFECYCLE_ENDED          CX_MAKE_STATUS(CX_STATUS_SEVERITY_ERROR, CX_FACILITY_CODEX_NATIVE, 0x0D + 0x200)
#define CX_STATUS_INVALID_DATA_STATE            CX_MAKE_STATUS(CX_STATUS_SEVERITY_ERROR, CX_FACILITY_CODEX_NATIVE, 0x0E + 0x200)
#define CX_STATUS_DATA_DOMAIN_OVERFLOW          CX_MAKE_STATUS(CX_STATUS_SEVERITY_ERROR, CX_FACILITY_CODEX_NATIVE, 0x0F + 0x200)
#define CX_STATUS_ALIGNMENT_INCONSISTENCY       CX_MAKE_STATUS(CX_STATUS_SEVERITY_ERROR, CX_FACILITY_CODEX_NATIVE, 0x10 + 0x200)

// array or raw data handling
#define CX_STATUS_DATA_BUFFER_TOO_SMALL         CX_MAKE_STATUS(CX_STATUS_SEVERITY_ERROR, CX_FACILITY_CODEX_NATIVE, 0x11 + 0x200)
#define CX_STATUS_BUFFER_UNDERFLOW              CX_MAKE_STATUS(CX_STATUS_SEVERITY_ERROR, CX_FACILITY_CODEX_NATIVE, 0x12 + 0x200)
#define CX_STATUS_BUFFER_OVERFLOW               CX_MAKE_STATUS(CX_STATUS_SEVERITY_ERROR, CX_FACILITY_CODEX_NATIVE, 0x13 + 0x200)
#define CX_STATUS_OUT_OF_RESOURCES              CX_MAKE_STATUS(CX_STATUS_SEVERITY_ERROR, CX_FACILITY_CODEX_NATIVE, 0x14 + 0x200)
#define CX_STATUS_OUT_OF_MEMORY                 CX_MAKE_STATUS(CX_STATUS_SEVERITY_ERROR, CX_FACILITY_CODEX_NATIVE, 0x15 + 0x200)
#define CX_STATUS_INDEX_OUT_OF_RANGE            CX_MAKE_STATUS(CX_STATUS_SEVERITY_ERROR, CX_FACILITY_CODEX_NATIVE, 0x16 + 0x200)
#define CX_STATUS_NO_MORE_ENTRIES               CX_MAKE_STATUS(CX_STATUS_SEVERITY_ERROR, CX_FACILITY_CODEX_NATIVE, 0x17 + 0x200)

// integer-arithmetic issues
#define CX_STATUS_ARITHMETIC_UNDERFLOW          CX_MAKE_STATUS(CX_STATUS_SEVERITY_ERROR, CX_FACILITY_CODEX_NATIVE, 0x18 + 0x200)
#define CX_STATUS_ARITHMETIC_OVERFLOW           CX_MAKE_STATUS(CX_STATUS_SEVERITY_ERROR, CX_FACILITY_CODEX_NATIVE, 0x19 + 0x200)

// valid, but not supported / can't be handled
#define CX_STATUS_UNSUPPORTED_DATA_VALUE        CX_MAKE_STATUS(CX_STATUS_SEVERITY_ERROR, CX_FACILITY_CODEX_NATIVE, 0x1A + 0x200)
#define CX_STATUS_UNSUPPORTED_DATA_TYPE         CX_MAKE_STATUS(CX_STATUS_SEVERITY_ERROR, CX_FACILITY_CODEX_NATIVE, 0x1B + 0x200)
#define CX_STATUS_UNSUPPORTED_DATA_SIZE         CX_MAKE_STATUS(CX_STATUS_SEVERITY_ERROR, CX_FACILITY_CODEX_NATIVE, 0x1C + 0x200)

#define CX_STATUS_DATA_OUT_OF_RANGE             CX_MAKE_STATUS(CX_STATUS_SEVERITY_ERROR, CX_FACILITY_CODEX_NATIVE, 0x1D + 0x200)

// key-value data structure statuses
#define CX_STATUS_KEY_ALREADY_EXISTS            CX_MAKE_STATUS(CX_STATUS_SEVERITY_ERROR, CX_FACILITY_CODEX_NATIVE, 0x1E + 0x200)
#define CX_STATUS_KEY_NOT_FOUND                 CX_MAKE_STATUS(CX_STATUS_SEVERITY_ERROR, CX_FACILITY_CODEX_NATIVE, 0x1F + 0x200)

//
// device errors
//
#define CX_STATUS_BAD_DEVICE_TYPE               CX_MAKE_STATUS(CX_STATUS_SEVERITY_ERROR, CX_FACILITY_CODEX_NATIVE, 0x00 + 0x300)
#define CX_STATUS_DEVICE_DATA_ERROR             CX_MAKE_STATUS(CX_STATUS_SEVERITY_ERROR, CX_FACILITY_CODEX_NATIVE, 0x01 + 0x300)
#define CX_STATUS_DEVICE_IO_ERROR               CX_MAKE_STATUS(CX_STATUS_SEVERITY_ERROR, CX_FACILITY_CODEX_NATIVE, 0x02 + 0x300)
#define CX_STATUS_DEVICE_NOT_INITIALIZED        CX_MAKE_STATUS(CX_STATUS_SEVERITY_ERROR, CX_FACILITY_CODEX_NATIVE, 0x03 + 0x300)
#define CX_STATUS_DEVICE_NOT_READY              CX_MAKE_STATUS(CX_STATUS_SEVERITY_ERROR, CX_FACILITY_CODEX_NATIVE, 0x04 + 0x300)
#define CX_STATUS_DEVICE_NOT_RESPONDING         CX_MAKE_STATUS(CX_STATUS_SEVERITY_ERROR, CX_FACILITY_CODEX_NATIVE, 0x05 + 0x300)
#define CX_STATUS_DEVICE_POWER_FAILURE          CX_MAKE_STATUS(CX_STATUS_SEVERITY_ERROR, CX_FACILITY_CODEX_NATIVE, 0x06 + 0x300)
#define CX_STATUS_DEVICE_NOT_FOUND              CX_MAKE_STATUS(CX_STATUS_SEVERITY_ERROR, CX_FACILITY_CODEX_NATIVE, 0x07 + 0x300)
#define CX_STATUS_INVALID_DEVICE_ID             CX_MAKE_STATUS(CX_STATUS_SEVERITY_ERROR, CX_FACILITY_CODEX_NATIVE, 0x08 + 0x300)
#define CX_STATUS_INVALID_DEVICE_TYPE           CX_MAKE_STATUS(CX_STATUS_SEVERITY_ERROR, CX_FACILITY_CODEX_NATIVE, 0x09 + 0x300)
#define CX_STATUS_INVALID_DEVICE_REQUEST        CX_MAKE_STATUS(CX_STATUS_SEVERITY_ERROR, CX_FACILITY_CODEX_NATIVE, 0x0A + 0x300)
#define CX_STATUS_INVALID_DEVICE_STATE          CX_MAKE_STATUS(CX_STATUS_SEVERITY_ERROR, CX_FACILITY_CODEX_NATIVE, 0x0B + 0x300)
#define CX_STATUS_DEVICE_CONFIGURATION_ERROR    CX_MAKE_STATUS(CX_STATUS_SEVERITY_ERROR, CX_FACILITY_CODEX_NATIVE, 0x0C + 0x300)
#define CX_STATUS_DEVICE_BUSY                   CX_MAKE_STATUS(CX_STATUS_SEVERITY_ERROR, CX_FACILITY_CODEX_NATIVE, 0x0D + 0x300)


// synchronization and timing errors
#define CX_STATUS_ABORTED_ON_TIMEOUT            CX_MAKE_STATUS(CX_STATUS_SEVERITY_ERROR, CX_FACILITY_CODEX_NATIVE, 0x01 + 0x400)
#define CX_STATUS_ABORTED_ON_CRITICAL_FAULT     CX_MAKE_STATUS(CX_STATUS_SEVERITY_ERROR, CX_FACILITY_CODEX_NATIVE, 0x02 + 0x400)
#define CX_STATUS_DATA_ALTERED_FROM_OUSIDE      CX_MAKE_STATUS(CX_STATUS_SEVERITY_ERROR, CX_FACILITY_CODEX_NATIVE, 0x03 + 0x400)
#define CX_STATUS_SYNCHRONIZATION_INCONSISTENCY CX_MAKE_STATUS(CX_STATUS_SEVERITY_ERROR, CX_FACILITY_CODEX_NATIVE, 0x04 + 0x400)


//
// generic status values -- avoid these in favor of the more specific ones wherever applicable!
//
#define CX_STATUS_ALREADY_INITIALIZED          CX_MAKE_STATUS(CX_STATUS_SEVERITY_ERROR, CX_FACILITY_CODEX_NATIVE, 0x00  + 0x500)
#define CX_STATUS_NOT_INITIALIZED              CX_MAKE_STATUS(CX_STATUS_SEVERITY_ERROR, CX_FACILITY_CODEX_NATIVE, 0x01  + 0x500)
#define CX_STATUS_UNEXPECTED_RACE_CONDITION    CX_MAKE_STATUS(CX_STATUS_SEVERITY_ERROR, CX_FACILITY_CODEX_NATIVE, 0x02  + 0x500)
#define CX_STATUS_INVALID_INTERNAL_STATE       CX_MAKE_STATUS(CX_STATUS_SEVERITY_ERROR, CX_FACILITY_CODEX_NATIVE, 0x03  + 0x500)
#define CX_STATUS_OUT_OF_RANGE                 CX_MAKE_STATUS(CX_STATUS_SEVERITY_ERROR, CX_FACILITY_CODEX_NATIVE, 0x04  + 0x500)
#define CX_STATUS_UNINITIALIZED_STATUS_VALUE   CX_MAKE_STATUS(CX_STATUS_SEVERITY_ERROR, CX_FACILITY_CODEX_NATIVE, 0x05  + 0x500)
#define CX_STATUS_INSUFFICIENT_RESOURCES       CX_MAKE_STATUS(CX_STATUS_SEVERITY_ERROR, CX_FACILITY_CODEX_NATIVE, 0x06  + 0x500)
#define CX_STATUS_NOT_FOUND                    CX_MAKE_STATUS(CX_STATUS_SEVERITY_ERROR, CX_FACILITY_CODEX_NATIVE, 0x07  + 0x500)
#define CX_STATUS_NOT_SUPPORTED                CX_MAKE_STATUS(CX_STATUS_SEVERITY_ERROR, CX_FACILITY_CODEX_NATIVE, 0x08  + 0x500)
#define CX_STATUS_ACCESS_DENIED                CX_MAKE_STATUS(CX_STATUS_SEVERITY_ERROR, CX_FACILITY_CODEX_NATIVE, 0x09  + 0x500)
#define CX_STATUS_UNEXPECTED_IO_ERROR          CX_MAKE_STATUS(CX_STATUS_SEVERITY_ERROR, CX_FACILITY_CODEX_NATIVE, 0x0A + 0x500)
#define CX_STATUS_ACCESS_VIOLATION             CX_MAKE_STATUS(CX_STATUS_SEVERITY_ERROR, CX_FACILITY_CODEX_NATIVE, 0x0B + 0x500)
#define CX_STATUS_ABANDONED                    CX_MAKE_STATUS(CX_STATUS_SEVERITY_ERROR, CX_FACILITY_CODEX_NATIVE, 0x0C + 0x500)
#define CX_STATUS_OBJECT_TYPE_MISMATCH         CX_MAKE_STATUS(CX_STATUS_SEVERITY_ERROR, CX_FACILITY_CODEX_NATIVE, 0x0D + 0x500)
#define CX_STATUS_INVALID_HANDLE               CX_MAKE_STATUS(CX_STATUS_SEVERITY_ERROR, CX_FACILITY_CODEX_NATIVE, 0x0E + 0x500)
#define CX_STATUS_NOT_READY                    CX_MAKE_STATUS(CX_STATUS_SEVERITY_ERROR, CX_FACILITY_CODEX_NATIVE, 0x0F + 0x500)
#define CX_STATUS_BUSY                         CX_MAKE_STATUS(CX_STATUS_SEVERITY_ERROR, CX_FACILITY_CODEX_NATIVE, 0x10 + 0x500)


//
// informational statuses
//
#define CX_STATUS_NOT_NEEDED_HINT              CX_MAKE_STATUS(CX_STATUS_SEVERITY_INFORMATIONAL, CX_FACILITY_CODEX_NATIVE, 0x00)
#define CX_STATUS_NOT_INITIALIZED_HINT         CX_MAKE_STATUS(CX_STATUS_SEVERITY_INFORMATIONAL, CX_FACILITY_CODEX_NATIVE, 0x01)
#define CX_STATUS_ALREADY_INITIALIZED_HINT     CX_MAKE_STATUS(CX_STATUS_SEVERITY_INFORMATIONAL, CX_FACILITY_CODEX_NATIVE, 0x02)
#define CX_STATUS_REINITIALIZED_HINT           CX_MAKE_STATUS(CX_STATUS_SEVERITY_INFORMATIONAL, CX_FACILITY_CODEX_NATIVE, 0x03)
#define CX_STATUS_FOUND                        CX_MAKE_STATUS(CX_STATUS_SEVERITY_INFORMATIONAL, CX_FACILITY_CODEX_NATIVE, 0x04)


#endif // _CX_STATUS_H_
