/*
* Copyright (c) 2020 Bitdefender
* SPDX-License-Identifier: Apache-2.0
*/

#ifdef crt_INC_SETTINGS_CRTDEFS_H
#include crt_INC_SETTINGS_CRTDEFS_H // define it to some .h file name/path if you want to provide settings
#endif


#ifndef _CRT_CRTDEFS_WRAPPER_
#define _CRT_CRTDEFS_WRAPPER_

#include "crt/crt_crtdefs.h"

#if ( !defined(CRT_SKIP_DECL_DBG_UNREFERENCED_PARAMETER) && (!defined(CRT_DEFAULT_SKIP_CRTDEFS_H_DECL) || defined(CRT_WANT_DECL_DBG_UNREFERENCED_PARAMETER))  )
#define DBG_UNREFERENCED_PARAMETER      CRT_DBG_UNREFERENCED_PARAMETER
#endif

#if ( !defined(CRT_SKIP_DECL_REL_UNREFERENCED_PARAMETER) && (!defined(CRT_DEFAULT_SKIP_CRTDEFS_H_DECL) || defined(CRT_WANT_DECL_REL_UNREFERENCED_PARAMETER))  )
#define REL_UNREFERENCED_PARAMETER      CRT_REL_UNREFERENCED_PARAMETER
#endif

#if ( !defined(CRT_SKIP_DECL_UNREFERENCED_LOCAL_VARIABLE) && (!defined(CRT_DEFAULT_SKIP_CRTDEFS_H_DECL) || defined(CRT_WANT_DECL_UNREFERENCED_LOCAL_VARIABLE))  )
#define UNREFERENCED_LOCAL_VARIABLE     CRT_UNREFERENCED_LOCAL_VARIABLE
#endif

#if ( !defined(CRT_SKIP_DECL_UNREFERENCED_PARAMETER) && (!defined(CRT_DEFAULT_SKIP_CRTDEFS_H_DECL) || defined(CRT_WANT_DECL_UNREFERENCED_PARAMETER))  )
#define UNREFERENCED_PARAMETER          CRT_UNREFERENCED_PARAMETER
#endif

#if ( !defined(CRT_SKIP_DECL___ELEMENTARY_DEFINITIONS) && (!defined(CRT_DEFAULT_SKIP_CRTDEFS_H_DECL) || defined(CRT_WANT_DECL___ELEMENTARY_DEFINITIONS))  )
#define __ELEMENTARY_DEFINITIONS        __CRT_ELEMENTARY_DEFINITIONS
#endif


#endif //_CRT_CRTDEFS_WRAPPER_
