/*
* Copyright (c) 2020 Bitdefender
* SPDX-License-Identifier: Apache-2.0
*/

#ifndef _VERSION_H_
#define _VERSION_H_

#include "../../include/ver.h"      // global version info

#define WINGUEST_VERSION_HIGH           GLOBAL_VERSION_MAJOR
#define WINGUEST_VERSION_LOW            GLOBAL_VERSION_MINOR
#define WINGUEST_VERSION_REVISION       GLOBAL_VERSION_REVISION
#define WINGUEST_VERSION_BUILD          GLOBAL_VERSION_BUILDNUMBER

#define WINGUEST_BUILD_DATE             __DATE__
#define WINGUEST_BUILD_TIME             __TIME__

#define WINGUEST_VERSIONSTAMP           ((((DWORD)WINGUEST_VERSION_REVISION) << 16) | ((DWORD)WINGUEST_VERSION_BUILD))

#ifdef VER_INTERNALNAME_STR
#undef VER_INTERNALNAME_STR
#endif
#define VER_INTERNALNAME_STR            "winguest.sys"

#ifdef VER_MODULE_REVISION
#undef VER_MODULE_REVISION
#endif
#define VER_MODULE_REVISION             WINGUEST_VERSION_REVISION

#ifdef VER_FILEVERSION
#undef VER_FILEVERSION
#endif
#define VER_FILEVERSION                 WINGUEST_VERSION_HIGH,WINGUEST_VERSION_LOW,WINGUEST_VERSION_REVISION,WINGUEST_VERSION_BUILD

#ifdef DBG
#define BDVER_FILEVERSION_MAJORMINORREVBLD2(x,y,z,w) #x "." #y "." #z "." #w ", DEBUG"
#else
#define BDVER_FILEVERSION_MAJORMINORREVBLD2(x,y,z,w) #x "." #y "." #z "." #w ", RELEASE"
#endif
#define BDVER_FILEVERSION_MAJORMINORREVBLD1(x,y,z,w) BDVER_FILEVERSION_MAJORMINORREVBLD2(x, y, z, w)

#ifdef VER_FILEVERSION_STR
#undef VER_FILEVERSION_STR
#endif
#define VER_FILEVERSION_STR             BDVER_FILEVERSION_MAJORMINORREVBLD1(WINGUEST_VERSION_HIGH, WINGUEST_VERSION_LOW, WINGUEST_VERSION_REVISION, WINGUEST_VERSION_BUILD)

#endif // _VERSION_H_
